name: hivez
description: "The cleanest way to use Hive in production. Type-safe, concurrency-safe, boilerplate-free. (Using hive_ce)"
version: 0.0.3
homepage: https://github.com/jozzdart/hivez
repository: https://github.com/jozzdart/hivez
issue_tracker: https://github.com/jozzdart/hivez/issues
topics:
  - hive
  - database
  - nosql
  - clean

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  hive_ce: ^2.13.2
  meta: ^1.16.0
  synchronized: ^3.2.0

dev_dependencies:
  test: ^1.26.1
  lints: ^5.1.1
